name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]  # Correct versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: python -m pip install --upgrade pip pipenv

    - name: Set PIPENV_PIPFILE environment variable
      run: echo "PIPENV_PIPFILE=$GITHUB_WORKSPACE/Pipfile" >> $GITHUB_ENV

    - name: Install dependencies (including dev packages)
      run: pipenv install --dev --deploy --ignore-pipfile

    - name: List Installed Packages
      run: pipenv run pip list

    - name: Run Tests with pytest
      run: pipenv run pytest --maxfail=1 --disable-warnings -v

