name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: python -m pip install --upgrade pip pipenv

    - name: Verify Pipfile and Set PIPENV_PIPFILE
      run: |
        echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
        export PIPENV_PIPFILE="$GITHUB_WORKSPACE/Pipfile"
        echo "Setting PIPENV_PIPFILE to $PIPENV_PIPFILE"
        
        # Verify if Pipfile exists at the specified path
        if [ -f "$PIPENV_PIPFILE" ]; then
          echo "Pipfile found at $PIPENV_PIPFILE."
        else
          echo "Pipfile NOT found at $PIPENV_PIPFILE."
          exit 1
        fi
      shell: bash

    - name: Install dependencies (including dev packages)
      env:
        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
      run: pipenv install --dev --deploy --ignore-pipfile

    - name: List Installed Packages
      env:
        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
      run: pipenv run pip list

    - name: Run Tests with pytest
      env:
        PIPENV_PIPFILE: "$GITHUB_WORKSPACE/Pipfile"
      run: pipenv run pytest --maxfail=1 --disable-warnings -v
