name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install runtime and development dependencies directly from pyproject.toml
    - name: Install all dependencies (runtime + dev)
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"  # Installs the package along with dev dependencies

    # Run tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ -v
