name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install dependencies with pipenv
      run: |
        pip install pipenv
        pipenv install --deploy --ignore-pipfile

    - name: Run tests
      run: |
        pipenv run pytest tests --maxfail=5 --disable-warnings

    - name: Lint with flake8
      run: |
        pipenv run pip install flake8
        pipenv run flake8 src tests  # Adjust paths as needed

    - name: Build Package
      run: |
        pipenv run python setup.py sdist bdist_wheel
