name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step 1: Install build tools
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    # Step 2: Build the package
    - name: Build the package
      run: |
        python -m build

    # Step 3: Install the built package with runtime dependencies
    - name: Install the package
      run: |
        pip install dist/*.whl  # Installs the package with runtime dependencies from pyproject.toml

    # Step 4: Install development dependencies explicitly
    - name: Install development dependencies
      run: |
        pip install pytest  # Manually installs pytest (from [project.optional-dependencies])

    # Step 5: Run tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ -v
