name: Publish Package

on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with "v", e.g., v1.0, v1.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for PyPI publishing with OIDC

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install build
          pip install twine

      - name: Build the package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: "__token__"
          password: "${{ secrets.TEST_PYPI_API_TOKEN }}"
          repository_url: "https://test.pypi.org/legacy/"
